// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqmqkGfnBKGs4I1qfQgUpZa5_ou-S9pBg',
    appId: '1:580757754203:web:384eee6a7052d4775f8a7e',
    messagingSenderId: '580757754203',
    projectId: 'how-about-coffee-pt',
    authDomain: 'how-about-coffee-pt.firebaseapp.com',
    storageBucket: 'how-about-coffee-pt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWxhMLD3K063Mwvv6yRyazQi6XTxUOq3w',
    appId: '1:580757754203:android:dc250f329d8b6dd95f8a7e',
    messagingSenderId: '580757754203',
    projectId: 'how-about-coffee-pt',
    storageBucket: 'how-about-coffee-pt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWO2SkyfbLJVPNh_un7M2s-zwNctXOLgQ',
    appId: '1:580757754203:ios:8a4fe86c7cd1df145f8a7e',
    messagingSenderId: '580757754203',
    projectId: 'how-about-coffee-pt',
    storageBucket: 'how-about-coffee-pt.appspot.com',
    androidClientId: '580757754203-omdo2l13i8kocbig8n6ib9tjt6do57o3.apps.googleusercontent.com',
    iosClientId: '580757754203-560kqdle0b2shpdbq8r18vsnhhsr5435.apps.googleusercontent.com',
    iosBundleId: 'com.brasizza.marcus',
  );
}
